### ISSUE TITLE
[chore] 마이페이지 등반 UI 수정

### ISSUE THREAD

**Issue by LeeJoEun-01** [ssu-it-project/cl-d-iOS#74]
## 💡 Issue

마이페이지 등반 기록에 있는 이미지를 수정합니다.

## 📝 Todo

- [x] 마이페이지 등반 기록에 있는 이미지 수정
- [x] 기록하기 완성 후 상세 페이지로 넘어가는 버튼 가리기
- [x] 커뮤니티 탭 멘트 삭제
- [x] 동영상 하나도 없을 때 멘트 추가
- [x] record 등록하기 api request 값 수정
